# This is a basic workflow to help you get started with Actions

name: pipeline

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main", "dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-validator:
    # The type of runner that the job will run on
    name: Run HTML Validator
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.1.1
        with:
          root: source/
          blacklist: admin/
          css: true
          log_level: DEBUG

      - uses: actions/upload-artifact@v3
        with:
          name: log
          path: source/actionsLogs/log.log

  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true

  jsDocs:
    name: Make jsDocs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build jsDocs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          recurse: true
          output_dir: ./source/jsDocs
